name: Test DAGs

on:
  push:
    paths:
      - 'dags/**'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --ignore E501 ./dags/ --verbose
    - name: Confirm Black code compliance (psf/black)
      run: |
        pip install pytest-black
        pytest ./dags/ --black -v
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        cd tests
        pytest tests.py --no-header -v \
          --doctest-modules --junitxml=../junit/test-results.xml \
          --cov=com --cov-report=xml --cov-report=html
